# Generated by Django 4.0.4 on 2022-08-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='admin',
        ),
    ]
